classdef Settings
    %SETTINGS Advanced raw Clarabel numerical settings.
    %
    % Settings mirrors the C ABI CoppClarabelSettings field set. Construct with
    % defaults, a struct, another Settings object, or name-value pairs:
    %
    %   settings = copp.clarabel.Settings(max_iter=120, tol_gap_rel=1e-7);

    properties
        max_iter (1,1) double {mustBeReal, mustBeFinite, mustBeInteger, mustBeNonnegative} = 0
        time_limit (1,1) double {mustBeReal, mustBePositive} = inf
        verbose (1,1) logical = false
        max_step_fraction (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        tol_gap_abs (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        tol_gap_rel (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        tol_feas (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        tol_infeas_abs (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        tol_infeas_rel (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        tol_ktratio (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        reduced_tol_gap_abs (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        reduced_tol_gap_rel (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        reduced_tol_feas (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        reduced_tol_infeas_abs (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        reduced_tol_infeas_rel (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        reduced_tol_ktratio (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        equilibrate_enable (1,1) logical = true
        equilibrate_max_iter (1,1) double {mustBeReal, mustBeFinite, mustBeInteger, mustBeNonnegative} = 0
        equilibrate_min_scaling (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        equilibrate_max_scaling (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        linesearch_backtrack_step (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 0.5
        min_switch_step_length (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        min_terminate_step_length (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        max_threads (1,1) double {mustBeReal, mustBeFinite, mustBeInteger, mustBeNonnegative} = 0
        direct_kkt_solver (1,1) logical = true
        direct_solve_method (1,1) string = "auto"
        static_regularization_enable (1,1) logical = true
        static_regularization_constant (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        static_regularization_proportional (1,1) double {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
        dynamic_regularization_enable (1,1) logical = true
        dynamic_regularization_eps (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        dynamic_regularization_delta (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        iterative_refinement_enable (1,1) logical = true
        iterative_refinement_reltol (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        iterative_refinement_abstol (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        iterative_refinement_max_iter (1,1) double {mustBeReal, mustBeFinite, mustBeInteger, mustBeNonnegative} = 0
        iterative_refinement_stop_ratio (1,1) double {mustBeReal, mustBeFinite, mustBePositive} = 1
        presolve_enable (1,1) logical = true
        input_sparse_dropzeros (1,1) logical = false
    end

    methods
        function obj = Settings(varargin)
            %SETTINGS Construct settings with optional overrides.
            obj = obj.apply_native_values(copp.clarabel.Options.default_native_values());

            if isempty(varargin)
                return
            end

            if isa(varargin{1}, 'copp.clarabel.Settings')
                obj = varargin{1};
                varargin(1) = [];
            elseif isstruct(varargin{1})
                obj = obj.apply_struct(varargin{1});
                varargin(1) = [];
            end

            if ~isempty(varargin)
                obj = obj.apply_overrides(varargin{:});
            end
        end

        function obj = apply_overrides(obj, varargin)
            %APPLY_OVERRIDES Return a copy with name-value overrides applied.
            if mod(numel(varargin), 2) ~= 0
                error("copp:InvalidArgument", ...
                    "Clarabel settings overrides must be name-value pairs.");
            end
            for k = 1:2:numel(varargin)
                obj = obj.set_named_value(varargin{k}, varargin{k + 1});
            end
        end

        function values = native_descriptor(obj)
            %NATIVE_DESCRIPTOR Return settings payload in C ABI field order.
            values = { ...
                obj.max_iter, ...
                obj.time_limit, ...
                double(obj.verbose), ...
                obj.max_step_fraction, ...
                obj.tol_gap_abs, ...
                obj.tol_gap_rel, ...
                obj.tol_feas, ...
                obj.tol_infeas_abs, ...
                obj.tol_infeas_rel, ...
                obj.tol_ktratio, ...
                obj.reduced_tol_gap_abs, ...
                obj.reduced_tol_gap_rel, ...
                obj.reduced_tol_feas, ...
                obj.reduced_tol_infeas_abs, ...
                obj.reduced_tol_infeas_rel, ...
                obj.reduced_tol_ktratio, ...
                double(obj.equilibrate_enable), ...
                obj.equilibrate_max_iter, ...
                obj.equilibrate_min_scaling, ...
                obj.equilibrate_max_scaling, ...
                obj.linesearch_backtrack_step, ...
                obj.min_switch_step_length, ...
                obj.min_terminate_step_length, ...
                obj.max_threads, ...
                double(obj.direct_kkt_solver), ...
                char(copp.internal.normalize_direct_solve_method(obj.direct_solve_method)), ...
                double(obj.static_regularization_enable), ...
                obj.static_regularization_constant, ...
                obj.static_regularization_proportional, ...
                double(obj.dynamic_regularization_enable), ...
                obj.dynamic_regularization_eps, ...
                obj.dynamic_regularization_delta, ...
                double(obj.iterative_refinement_enable), ...
                obj.iterative_refinement_reltol, ...
                obj.iterative_refinement_abstol, ...
                obj.iterative_refinement_max_iter, ...
                obj.iterative_refinement_stop_ratio, ...
                double(obj.presolve_enable), ...
                double(obj.input_sparse_dropzeros)};
        end
    end

    methods (Access = private)
        function obj = apply_native_values(obj, values)
            %APPLY_NATIVE_VALUES Fill fields from Clarabel options default payload.
            names = obj.field_names();
            for k = 1:numel(names)
                value = values{k + 6};
                if names(k) == "direct_solve_method"
                    value = copp.internal.clarabel_direct_solve_method_name(value);
                end
                obj.(names(k)) = value;
            end
        end

        function obj = apply_struct(obj, source)
            fields = string(fieldnames(source));
            for k = 1:numel(fields)
                obj = obj.set_named_value(fields(k), source.(fields(k)));
            end
        end

        function obj = set_named_value(obj, name, value)
            name = string(name);
            if strlength(name) == 0
                error("copp:InvalidArgument", "Clarabel settings field name must not be empty.");
            end
            if ~any(name == obj.field_names())
                error("copp:InvalidArgument", "Unknown Clarabel settings field '%s'.", name);
            end
            if name == "direct_solve_method"
                value = copp.internal.normalize_direct_solve_method(value);
            end
            obj.(name) = value;
        end
    end

    methods (Static, Access = private)
        function names = field_names()
            names = [ ...
                "max_iter", ...
                "time_limit", ...
                "verbose", ...
                "max_step_fraction", ...
                "tol_gap_abs", ...
                "tol_gap_rel", ...
                "tol_feas", ...
                "tol_infeas_abs", ...
                "tol_infeas_rel", ...
                "tol_ktratio", ...
                "reduced_tol_gap_abs", ...
                "reduced_tol_gap_rel", ...
                "reduced_tol_feas", ...
                "reduced_tol_infeas_abs", ...
                "reduced_tol_infeas_rel", ...
                "reduced_tol_ktratio", ...
                "equilibrate_enable", ...
                "equilibrate_max_iter", ...
                "equilibrate_min_scaling", ...
                "equilibrate_max_scaling", ...
                "linesearch_backtrack_step", ...
                "min_switch_step_length", ...
                "min_terminate_step_length", ...
                "max_threads", ...
                "direct_kkt_solver", ...
                "direct_solve_method", ...
                "static_regularization_enable", ...
                "static_regularization_constant", ...
                "static_regularization_proportional", ...
                "dynamic_regularization_enable", ...
                "dynamic_regularization_eps", ...
                "dynamic_regularization_delta", ...
                "iterative_refinement_enable", ...
                "iterative_refinement_reltol", ...
                "iterative_refinement_abstol", ...
                "iterative_refinement_max_iter", ...
                "iterative_refinement_stop_ratio", ...
                "presolve_enable", ...
                "input_sparse_dropzeros"];
        end
    end
end
