function result = solve_expert(problem, options)
%SOLVE_EXPERT Solve TOPP3-SOCP and return raw Clarabel diagnostics.
%
% RESULT.profile is available only when RESULT.has_profile is true; its a and
% b fields are PROBLEM.s_len-by-1 columns. Raw Clarabel vectors are stored as
% double columns. This call linearizes third-order constraints and mutates the
% native Robot cache.
%
% PROBLEM may be the shared copp.solver.topp3.Problem descriptor or the
% solver-specific topp3_socp.Problem facade.
arguments
    problem (1,1) copp.solver.topp3.Problem
    options (1,1) copp.clarabel.Options = copp.solver.topp3_socp.Options()
end

[robot_id, idx_s_start, a_linearization, a_start, a_final, b_start, b_final, ...
    num_stationary_max_start, num_stationary_max_end, a_linearization_floor] = problem.native_descriptor();
option_args = options.native_descriptor();

[has_profile, a, b, num_stationary_start, num_stationary_end, x, z, s_vec, ...
    status_code, obj_val, obj_val_dual, solve_time, iterations, r_prim, r_dual, ...
    objective_value, objective_terms, method_code, threads, direct, nnz_a, nnz_l] = ...
    copp.internal.copp_mex( ...
    'topp3_socp_solve_expert', ...
    robot_id, idx_s_start, a_linearization, a_start, a_final, b_start, b_final, ...
    num_stationary_max_start, num_stationary_max_end, a_linearization_floor, ...
    option_args{:});

profile = [];
if logical(has_profile)
    profile = copp.Profile3rd(a, b, ...
        num_stationary=[num_stationary_start, num_stationary_end]);
end

linsolver = struct( ...
    'method', copp.internal.clarabel_direct_solve_method_name(method_code), ...
    'threads', double(threads), ...
    'direct', logical(direct), ...
    'nnz_a', double(nnz_a), ...
    'nnz_l', double(nnz_l));

result = copp.solver.topp3_socp.Result( ...
    logical(has_profile), profile, x, z, s_vec, ...
    copp.internal.clarabel_solver_status_name(status_code), ...
    obj_val, obj_val_dual, solve_time, iterations, r_prim, r_dual, ...
    linsolver, objective_value, objective_terms);
end
