#ifndef COPP_PATH_H
#define COPP_PATH_H

/*
 * Generated by bindings/c/scripts/generate_headers.ps1.
 * Do not edit by hand; update src/ffi/c and regenerate.
 */

/**
 * \file path.h
 * \brief Path construction, metadata, evaluation, and callback path APIs.
 * \ingroup copp_path
 */

#include <stddef.h>
#include <math.h>
#include "copp/core.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \addtogroup copp_path
 * @{
 */

/**
 * Opaque C handle for a library-owned `Path`.
 *
 * Create with `copp_path_from_waypoints_interpolating`,
 * `copp_path_from_waypoints_fitting`, `copp_path_from_parametric`,
 * `copp_path_from_evaluator_2nd`, or `copp_path_from_evaluator_3rd` and
 * release exactly once with `copp_path_free`. C callers must not inspect or
 * allocate this type directly.
 */
typedef struct CoppPath CoppPath;

/**
 * C-compatible third-order automatic-differentiation scalar.
 *
 * `v` stores the scalar value, while `d1`, `d2`, and `d3` store derivatives
 * with respect to the path parameter `s`. Parametric path callbacks receive a
 * seeded value (`d1 = 1`) and should return one `CoppJet3` per path dimension.
 */
typedef struct CoppJet3 {
    /**
     * Function value.
     */
    double v;
    /**
     * First derivative with respect to `s`.
     */
    double d1;
    /**
     * Second derivative with respect to `s`.
     */
    double d2;
    /**
     * Third derivative with respect to `s`.
     */
    double d3;
} CoppJet3;

/**
 * C ABI path out-of-range behavior.
 */
typedef enum CoppPathOutOfRangeMode {
    /**
     * Return an error when a query parameter is outside `[s_min, s_max]`.
     */
    COPP_PATH_OUT_OF_RANGE_MODE_ERROR = 0,
    /**
     * Clamp query parameters into `[s_min, s_max]`.
     */
    COPP_PATH_OUT_OF_RANGE_MODE_CLAMP = 1,
} CoppPathOutOfRangeMode;

/**
 * C ABI waypoint-spline parametrization.
 */
typedef enum CoppPathParametrization {
    /**
     * Uniform parameter spacing between waypoints.
     */
    COPP_PATH_PARAMETRIZATION_UNIFORM = 0,
} CoppPathParametrization;

/**
 * Options for waypoint spline path construction.
 *
 * `start_state` and `end_state` are optional matrix views of shape
 * `dim x ((order - 1) / 2)`. Use an empty matrix view (`data = NULL`,
 * `rows = cols = 0`), such as `COPP_MATRIX_VIEW_F64_COLUMN_MAJOR(NULL, 0, 0)`
 * from C, for zero boundary derivatives.
 */
typedef struct CoppPathOptions {
    /**
     * Spline order. Must be odd and at least 3. Common values are 3, 5, and 7.
     */
    size_t order;
    /**
     * Lower bound of the path parameter range.
     */
    double s_min;
    /**
     * Upper bound of the path parameter range.
     */
    double s_max;
    /**
     * Behavior for out-of-range path evaluation.
     */
    enum CoppPathOutOfRangeMode out_of_range_mode;
    /**
     * Waypoint parametrization mode.
     */
    enum CoppPathParametrization parametrization;
    /**
     * Boundary derivatives at `s_min`, or empty for zero boundary derivatives.
     */
    struct CoppMatrixViewF64 start_state;
    /**
     * Boundary derivatives at `s_max`, or empty for zero boundary derivatives.
     */
    struct CoppMatrixViewF64 end_state;
} CoppPathOptions;

/**
 * C callback for evaluating a scalar-parametric path with automatic derivatives.
 *
 * The callback receives one seeded `CoppJet3` path parameter and must write
 * `dim` `CoppJet3` values into `q`. COPP extracts each returned value and
 * its first three derivatives to serve the existing path evaluation and robot
 * sampling APIs.
 */
typedef enum CoppStatus (*CoppPathParametricFn)(void *user_data,
                                                size_t dim,
                                                struct CoppJet3 s,
                                                struct CoppJet3 *q);

/**
 * C callback for evaluating `q`, `dq`, and `ddq`.
 *
 * The callback receives `n` path samples in `s` and must write column-major
 * `dim x n` matrices into `q`, `dq`, and `ddq`.
 */
typedef enum CoppStatus (*CoppPathEvaluate2ndFn)(void *user_data,
                                                 size_t dim,
                                                 size_t n,
                                                 const double *s,
                                                 double *q,
                                                 double *dq,
                                                 double *ddq);

/**
 * C callback for evaluating `q`, `dq`, `ddq`, and `dddq`.
 *
 * The callback receives `n` path samples in `s` and must write column-major
 * `dim x n` matrices into `q`, `dq`, `ddq`, and `dddq`.
 */
typedef enum CoppStatus (*CoppPathEvaluate3rdFn)(void *user_data,
                                                 size_t dim,
                                                 size_t n,
                                                 const double *s,
                                                 double *q,
                                                 double *dq,
                                                 double *ddq,
                                                 double *dddq);

#ifdef __cplusplus
}
#endif

/**
 * Construct a constant automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_constant(double x)
{
    struct CoppJet3 out = {x, 0.0, 0.0, 0.0};
    return out;
}

/**
 * Add two automatic-differentiation scalars.
 */
static inline struct CoppJet3 copp_add(struct CoppJet3 a, struct CoppJet3 b)
{
    struct CoppJet3 out = {a.v + b.v, a.d1 + b.d1, a.d2 + b.d2, a.d3 + b.d3};
    return out;
}

/**
 * Add a floating-point constant to an automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_add_f64(struct CoppJet3 a, double b)
{
    struct CoppJet3 out = {a.v + b, a.d1, a.d2, a.d3};
    return out;
}

/**
 * Subtract two automatic-differentiation scalars.
 */
static inline struct CoppJet3 copp_sub(struct CoppJet3 a, struct CoppJet3 b)
{
    struct CoppJet3 out = {a.v - b.v, a.d1 - b.d1, a.d2 - b.d2, a.d3 - b.d3};
    return out;
}

/**
 * Subtract a floating-point constant from an automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_sub_f64(struct CoppJet3 a, double b)
{
    struct CoppJet3 out = {a.v - b, a.d1, a.d2, a.d3};
    return out;
}

/**
 * Subtract an automatic-differentiation scalar from a floating-point constant.
 */
static inline struct CoppJet3 copp_f64_sub(double a, struct CoppJet3 b)
{
    struct CoppJet3 out = {a - b.v, -b.d1, -b.d2, -b.d3};
    return out;
}

/**
 * Negate an automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_neg(struct CoppJet3 x)
{
    struct CoppJet3 out = {-x.v, -x.d1, -x.d2, -x.d3};
    return out;
}

/**
 * Multiply two automatic-differentiation scalars.
 */
static inline struct CoppJet3 copp_mul(struct CoppJet3 a, struct CoppJet3 b)
{
    struct CoppJet3 out = {
        a.v * b.v,
        a.d1 * b.v + a.v * b.d1,
        a.d2 * b.v + 2.0 * a.d1 * b.d1 + a.v * b.d2,
        a.d3 * b.v + 3.0 * (a.d2 * b.d1 + a.d1 * b.d2) + a.v * b.d3};
    return out;
}

/**
 * Multiply an automatic-differentiation scalar by a floating-point constant.
 */
static inline struct CoppJet3 copp_mul_f64(struct CoppJet3 a, double b)
{
    struct CoppJet3 out = {a.v * b, a.d1 * b, a.d2 * b, a.d3 * b};
    return out;
}

/**
 * Divide a floating-point constant by an automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_f64_div(double a, struct CoppJet3 b)
{
    const double inv = 1.0 / b.v;
    const double inv2 = inv * inv;
    const double inv3 = inv2 * inv;
    const double inv4 = inv3 * inv;
    const double d1sq = b.d1 * b.d1;
    struct CoppJet3 out = {
        a * inv,
        -a * inv2 * b.d1,
        a * (2.0 * inv3 * d1sq - inv2 * b.d2),
        a * (-6.0 * inv4 * d1sq * b.d1 + 6.0 * inv3 * b.d1 * b.d2 - inv2 * b.d3)};
    return out;
}

/**
 * Divide an automatic-differentiation scalar by a floating-point constant.
 */
static inline struct CoppJet3 copp_div_f64(struct CoppJet3 a, double b)
{
    return copp_mul_f64(a, 1.0 / b);
}

/**
 * Divide two automatic-differentiation scalars.
 */
static inline struct CoppJet3 copp_div(struct CoppJet3 a, struct CoppJet3 b)
{
    return copp_mul(a, copp_f64_div(1.0, b));
}

/**
 * Apply sine to an automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_sin(struct CoppJet3 x)
{
    const double sv = sin(x.v);
    const double cv = cos(x.v);
    const double d1sq = x.d1 * x.d1;
    struct CoppJet3 out = {
        sv,
        cv * x.d1,
        -sv * d1sq + cv * x.d2,
        -cv * d1sq * x.d1 - 3.0 * sv * x.d1 * x.d2 + cv * x.d3};
    return out;
}

/**
 * Apply cosine to an automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_cos(struct CoppJet3 x)
{
    const double sv = sin(x.v);
    const double cv = cos(x.v);
    const double d1sq = x.d1 * x.d1;
    struct CoppJet3 out = {
        cv,
        -sv * x.d1,
        -cv * d1sq - sv * x.d2,
        sv * d1sq * x.d1 - 3.0 * cv * x.d1 * x.d2 - sv * x.d3};
    return out;
}

/**
 * Apply exponential to an automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_exp(struct CoppJet3 x)
{
    const double ev = exp(x.v);
    const double d1sq = x.d1 * x.d1;
    struct CoppJet3 out = {
        ev,
        ev * x.d1,
        ev * (d1sq + x.d2),
        ev * (d1sq * x.d1 + 3.0 * x.d1 * x.d2 + x.d3)};
    return out;
}

/**
 * Apply natural logarithm to an automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_log(struct CoppJet3 x)
{
    const double inv = 1.0 / x.v;
    const double inv2 = inv * inv;
    const double inv3 = inv2 * inv;
    const double d1sq = x.d1 * x.d1;
    struct CoppJet3 out = {
        log(x.v),
        inv * x.d1,
        -inv2 * d1sq + inv * x.d2,
        2.0 * inv3 * d1sq * x.d1 - 3.0 * inv2 * x.d1 * x.d2 + inv * x.d3};
    return out;
}

/**
 * Apply square root to an automatic-differentiation scalar.
 */
static inline struct CoppJet3 copp_sqrt(struct CoppJet3 x)
{
    const double sqrtv = sqrt(x.v);
    const double inv_sqrt = 1.0 / sqrtv;
    const double inv_v_sqrt = inv_sqrt / x.v;
    const double inv_v2_sqrt = inv_v_sqrt / x.v;
    const double d1sq = x.d1 * x.d1;
    struct CoppJet3 out = {
        sqrtv,
        0.5 * inv_sqrt * x.d1,
        -0.25 * inv_v_sqrt * d1sq + 0.5 * inv_sqrt * x.d2,
        0.375 * inv_v2_sqrt * d1sq * x.d1 - 0.75 * inv_v_sqrt * x.d1 * x.d2 + 0.5 * inv_sqrt * x.d3};
    return out;
}

/**
 * Raise an automatic-differentiation scalar to an integer power.
 */
static inline struct CoppJet3 copp_powi(struct CoppJet3 x, int n)
{
    if (n == 0) {
        return copp_constant(1.0);
    }

    const double nf = (double)n;
    const double coeff2 = nf * (nf - 1.0);
    const double coeff3 = coeff2 * (nf - 2.0);
    const double dv = nf * pow(x.v, nf - 1.0);
    const double ddv = coeff2 == 0.0 ? 0.0 : coeff2 * pow(x.v, nf - 2.0);
    const double dddv = coeff3 == 0.0 ? 0.0 : coeff3 * pow(x.v, nf - 3.0);
    const double d1sq = x.d1 * x.d1;
    struct CoppJet3 out = {
        pow(x.v, (double)n),
        dv * x.d1,
        ddv * d1sq + dv * x.d2,
        dddv * d1sq * x.d1 + 3.0 * ddv * x.d1 * x.d2 + dv * x.d3};
    return out;
}

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Write default waypoint spline options into `out_options`.
 *
 * Defaults are quintic order 5, uniform parametrization, zero boundary
 * derivatives, and out-of-range errors.
 *
 * \par Safety
 * `out_options` must be valid for one `CoppPathOptions` write.
 */
enum CoppStatus copp_path_default_options(double s_min,
                                          double s_max,
                                          struct CoppPathOptions *out_options);

/**
 * Build an interpolating waypoint spline path.
 *
 * `waypoints` must be a matrix view of shape `dim x n_points`, where each
 * column is one waypoint. The spline interpolates every waypoint column.
 * `options.start_state` and `options.end_state` may be empty to use zero
 * boundary derivatives.
 *
 * Column-major input with `leading_dim >= rows` avoids a temporary layout
 * copy while building the spline coefficients. Row-major input is accepted
 * and copied once into column-major temporary storage. Spline construction
 * still allocates library-owned polynomial coefficients for the returned path.
 *
 * On success, `*out_path` receives a non-null handle that must be released
 * with `copp_path_free`.
 *
 * # API stability
 * The waypoint path constructors are currently unstable: their names,
 * signatures, and option types may change as additional waypoint
 * path-construction algorithms are introduced. `copp_path_from_waypoints` is
 * an equivalent alias of this function.
 *
 * # Example
 * The example below builds a two-dimensional spline path from column-major
 * waypoint coordinates.
 *
 * ```c
 * enum { DIM = 2, NUM_WAYPOINTS = 4 };
 * double waypoints[DIM * NUM_WAYPOINTS] = {
 *     0.0, 0.0,
 *     0.3, 0.2,
 *     0.7, 0.8,
 *     1.0, 1.0,
 * };
 *
 * struct CoppPathOptions options;
 * struct CoppPath *path = NULL;
 * check(copp_path_default_options(0.0, 1.0, &options));
 * check(copp_path_from_waypoints_interpolating(
 *     COPP_MATRIX_VIEW_F64_COLUMN_MAJOR(waypoints, DIM, NUM_WAYPOINTS),
 *     options,
 *     &path));
 *
 * copp_path_free(path);
 * ```
 *
 * \par Safety
 * Non-empty matrix views in `waypoints` and `options` must point to valid
 * `double` arrays for their declared layouts for the duration of this call.
 * `out_path` must be valid for one `CoppPath*` write.
 */
enum CoppStatus copp_path_from_waypoints_interpolating(struct CoppMatrixViewF64 waypoints,
                                                       struct CoppPathOptions options,
                                                       struct CoppPath **out_path);

/**
 * Build an interpolating waypoint spline path.
 *
 * This is an equivalent alias of `copp_path_from_waypoints_interpolating`
 * with identical arguments, behavior, and status codes. Both names remain
 * supported and share the unstable status of the waypoint path constructors.
 *
 * \par Safety
 * Same requirements as `copp_path_from_waypoints_interpolating`.
 */
enum CoppStatus copp_path_from_waypoints(struct CoppMatrixViewF64 waypoints,
                                         struct CoppPathOptions options,
                                         struct CoppPath **out_path);

/**
 * Options for tolerance-bounded waypoint fitting.
 *
 * Use `copp_smoothing_default_options` first, then override only the fields
 * you need. Empty borrowed slices (`data = NULL`, `len = 0`) select the
 * documented defaults. Borrowed slices are read only during
 * `copp_path_from_waypoints_fitting`; the returned path does not keep them.
 *
 * This options type is currently unstable: its fields and layout may change
 * as additional waypoint path-construction algorithms are introduced.
 *
 * # Example
 * The example below fits translational rows `0..=2` to `1e-3` input units and
 * rotary rows `3..=4` to `1e-2` input units. Tolerance entries follow `axes`
 * order.
 *
 * ```c
 * size_t axes[] = {0, 1, 2, 3, 4};
 * double tolerances[] = {1e-3, 1e-3, 1e-3, 1e-2, 1e-2};
 * struct CoppSmoothingOptions options;
 * check(copp_smoothing_default_options(&options));
 * options.axes = (struct CoppSliceUsize){axes, 5};
 * options.tolerance_per_axis = (struct CoppSliceF64){tolerances, 5};
 * ```
 */
typedef struct CoppSmoothingOptions {
    /**
     * Absolute tolerance broadcast to every selected axis when
     * `tolerance_per_axis` is empty.
     *
     * The value is expressed in each selected row's input units and must be
     * finite and strictly positive. The default is `0.001`.
     */
    double tolerance;
    /**
     * Optional per-axis absolute tolerances.
     *
     * When non-empty, this replaces `tolerance`. Its length must equal the
     * number of selected axes, and entry `i` applies to input row `axes[i]`:
     * the order follows `axes`, not the row index. When `axes` is empty, the
     * order is the natural row order `0..rows`. Every entry must be finite and
     * strictly positive, in the corresponding row's input units.
     */
    struct CoppSliceF64 tolerance_per_axis;
    /**
     * Optional 0-based input rows allowed to deviate from their reference
     * polylines.
     *
     * Empty selects every row. A non-empty list must contain distinct,
     * in-range row indices; its order also defines the order of
     * `tolerance_per_axis` and of the report's `axes` and `max_errors`.
     * Unselected rows keep quintic `C4` interpolation through all waypoint
     * columns, with zero first and second parameter derivatives at both ends.
     */
    struct CoppSliceUsize axes;
    /**
     * Optional common path parameter assigned to each waypoint column.
     *
     * Empty assigns the columns uniformly on `[0, 1]`. A non-empty list must
     * contain one finite, strictly increasing entry per column; its first and
     * last entries become the path parameter range. Relative spacing affects
     * the fitted geometry, not only the returned parameter range.
     */
    struct CoppSliceF64 parameters;
    /**
     * Maximum number of adaptive knot-refinement passes.
     *
     * The default is 20. Reaching this limit before the whole-interval audit
     * passes returns `COPP_STATUS_PATH_SMOOTHING`.
     */
    size_t max_refinements;
    /**
     * Maximum number of polynomial spans used by the selected axes.
     *
     * The default is 20000. Spans of the separate unselected-axis
     * interpolant do not consume this budget.
     */
    size_t max_segments;
    /**
     * Behavior for out-of-range evaluation of the returned path.
     *
     * The default is `COPP_PATH_OUT_OF_RANGE_MODE_ERROR`. Clamping affects
     * later queries, not fitting or auditing.
     */
    enum CoppPathOutOfRangeMode out_of_range_mode;
} CoppSmoothingOptions;

/**
 * Diagnostics recorded while constructing a tolerance-fitted waypoint path.
 *
 * Obtain this report with `copp_path_smoothing_report`. `axes`, `segments`,
 * and `interpolated_segments` describe the final representation, while
 * `refinements`, `fitting_rows`, and `checked_intervals` are cumulative work
 * counters. None of these values is an optimality or run-time guarantee.
 * Both vectors are library-owned and must be released together with
 * `copp_smoothing_report_free`.
 *
 * This report type is currently unstable: its fields and layout may change as
 * additional waypoint path-construction algorithms are introduced.
 */
typedef struct CoppSmoothingReport {
    /**
     * Selected 0-based input-row indices, in tolerance/report order.
     */
    struct CoppVecUsize axes;
    /**
     * Number of final polynomial spans shared by the selected axes.
     */
    size_t segments;
    /**
     * Number of spans in the separate unselected-axis interpolant.
     *
     * This is zero when every row is selected and is not included in
     * `segments` or the `max_segments` budget.
     */
    size_t interpolated_segments;
    /**
     * Number of completed local knot-refinement passes.
     */
    size_t refinements;
    /**
     * Number of discrete or quadrature fitting rows assembled, counting rows
     * assembled again during local refits.
     */
    size_t fitting_rows;
    /**
     * Number of reference-polyline intervals visited by numerical audits,
     * including revisits and the final full audit.
     */
    size_t checked_intervals;
    /**
     * Final whole-domain absolute-error bound for each selected axis.
     *
     * Values are in input units and follow `axes` order. They are
     * Bernstein-derived numerical bounds computed with ordinary
     * floating-point arithmetic, not sampled maxima or formal certificates.
     */
    struct CoppVecF64 max_errors;
} CoppSmoothingReport;

/**
 * Write default tolerance-bounded fitting options into `out_options`.
 *
 * Defaults fit every row with absolute tolerance `0.001`, assign waypoint
 * parameters uniformly on `[0, 1]`, allow 20 refinement passes and 20000
 * selected-axis spans, and reject out-of-range queries. All borrowed slices
 * are empty.
 *
 * \par Safety
 * `out_options` must be valid for one `CoppSmoothingOptions` write.
 */
enum CoppStatus copp_smoothing_default_options(struct CoppSmoothingOptions *out_options);

/**
 * Build a tolerance-bounded waypoint-fitting path.
 *
 * `waypoints` must be a finite matrix view of shape `dim x n_points` with
 * `dim > 0` and `n_points >= 2`, where each column is one waypoint. Each
 * column receives a common path parameter (`options.parameters`, or uniform
 * on `[0, 1]` when empty), and adjacent columns are joined linearly into a
 * reference polyline. The selected axes (`options.axes`, or every row when
 * empty) are approximated by one adaptive nonuniform quintic B-spline with
 * `C4` continuity whose same-parameter absolute deviation from the reference
 * polyline stays within each axis tolerance. The error is audited over every
 * complete reference interval, not only at the waypoints.
 *
 * Unlike `copp_path_from_waypoints_interpolating`, the fitted path does not
 * pass through interior waypoints: selected axes may deviate within their
 * tolerances, while the first and last waypoints are retained. Unselected
 * rows keep quintic `C4` interpolation through every column. Derivatives
 * returned by path evaluation are with respect to the path parameter `s`,
 * not time. Use `copp_path_smoothing_report` to inspect the selected axes,
 * the final per-axis error bounds, and the refinement work.
 *
 * Column-major input with `leading_dim >= rows` is read without a temporary
 * layout copy. Row-major input is accepted and copied once into column-major
 * temporary storage. The returned path owns its fitted representation and
 * does not borrow `waypoints` or the slices in `options` after the call.
 *
 * On success, `*out_path` receives a non-null handle that must be released
 * with `copp_path_free`.
 *
 * # API stability
 * The waypoint path constructors and `CoppSmoothingOptions` /
 * `CoppSmoothingReport` are currently unstable: their names, signatures, and
 * option types may change as additional waypoint path-construction
 * algorithms are introduced.
 *
 * \par Errors
 * Returns `COPP_STATUS_PATH_SMOOTHING` when the waypoint values, dimensions,
 * axes, tolerances, or parameters violate their contracts, when the
 * selected-axis span count exceeds `options.max_segments`, when refinement
 * exhausts `options.max_refinements` or the parameter resolution, when the
 * banded fit encounters an unusable numerical system, or when the final
 * whole-interval audit fails. An unchecked or relaxed approximation is never
 * returned.
 *
 * # Example
 * The example below fits a two-dimensional waypoint path within `1e-3` input
 * units and reads the final error bound of each axis.
 *
 * ```c
 * enum { DIM = 2, NUM_WAYPOINTS = 5 };
 * double waypoints[DIM * NUM_WAYPOINTS] = {
 *     0.0, 0.0,
 *     0.25, 0.4,
 *     0.5, 0.5,
 *     0.75, 0.4,
 *     1.0, 0.0,
 * };
 *
 * struct CoppSmoothingOptions options;
 * struct CoppPath *path = NULL;
 * check(copp_smoothing_default_options(&options));
 * options.tolerance = 1e-3;
 * check(copp_path_from_waypoints_fitting(
 *     COPP_MATRIX_VIEW_F64_COLUMN_MAJOR(waypoints, DIM, NUM_WAYPOINTS),
 *     options,
 *     &path));
 *
 * bool has_report = false;
 * struct CoppSmoothingReport report = {0};
 * check(copp_path_smoothing_report(path, &has_report, &report));
 * for (size_t i = 0; i < report.axes.len; ++i) {
 *     printf("axis %zu: %.3e\n", report.axes.data[i], report.max_errors.data[i]);
 * }
 * copp_smoothing_report_free(report);
 * copp_path_free(path);
 * ```
 *
 * \par Safety
 * Non-empty matrix views and slices in `waypoints` and `options` must point
 * to valid arrays for their declared layouts for the duration of this call.
 * `out_path` must be valid for one `CoppPath*` write.
 */
enum CoppStatus copp_path_from_waypoints_fitting(struct CoppMatrixViewF64 waypoints,
                                                 struct CoppSmoothingOptions options,
                                                 struct CoppPath **out_path);

/**
 * Return the construction report of a tolerance-fitted waypoint path.
 *
 * For a path built by `copp_path_from_waypoints_fitting`, `*out_has_report`
 * receives `true` and `*out_report` receives a library-owned report that must
 * be released with `copp_smoothing_report_free`. For any other path,
 * `*out_has_report` receives `false` and `*out_report` receives an empty
 * report with null vectors and zero counters; releasing it is allowed.
 *
 * \par Safety
 * `path` must be a non-null handle created by this module.
 * `out_has_report` must be valid for one `bool` write and `out_report` for
 * one `CoppSmoothingReport` write.
 */
enum CoppStatus copp_path_smoothing_report(const struct CoppPath *path,
                                           bool *out_has_report,
                                           struct CoppSmoothingReport *out_report);

/**
 * Release memory owned by a `CoppSmoothingReport`.
 *
 * Passing an empty report is allowed and has no effect. Passing an
 * already-freed report is invalid.
 *
 * \par Safety
 * `report` must either be empty/null or have been returned by
 * `copp_path_smoothing_report`. Passing arbitrary pointers or modified
 * capacity fields is invalid.
 */
void copp_smoothing_report_free(struct CoppSmoothingReport report);

/**
 * Build a path from a scalar-parametric C callback.
 *
 * COPP calls `evaluate` once per path sample with a seeded `CoppJet3` value
 * for `s`. The callback writes `dim` output entries describing only `q(s)`;
 * the returned `CoppJet3` derivative fields provide `dq`, `ddq`, and `dddq`.
 * Use the inline helpers in `copp/path.h` such as `copp_add`, `copp_mul`, and
 * `copp_sin` to write formulas without hand-differentiating them.
 *
 * The resulting path supports position, second-order, and third-order
 * evaluation and can be sampled by `copp_robot_sample_path_2nd` or
 * `copp_robot_sample_path_3rd`.
 *
 * The callback pointer and `user_data` are borrowed by the created path and
 * must remain valid until `copp_path_free` is called. Calls into the callback
 * are serialized per path handle.
 *
 * On success, `*out_path` receives a non-null handle that must be released
 * with `copp_path_free`.
 *
 * # Example
 * The example below builds a one-dimensional `q(s) = sin(2*pi*s)` path.
 *
 * ```c
 * static enum CoppStatus eval_path_parametric(
 *     void *user_data,
 *     size_t dim,
 *     struct CoppJet3 s,
 *     struct CoppJet3 *q)
 * {
 *     (void)user_data;
 *     if (dim != 1 || q == NULL) {
 *         return COPP_STATUS_INVALID_ARGUMENT;
 *     }
 *     q[0] = copp_sin(copp_mul_f64(s, 6.28318530717958647692));
 *     return COPP_STATUS_OK;
 * }
 *
 * struct CoppPath *path = NULL;
 * check(copp_path_from_parametric(1, 0.0, 1.0, eval_path_parametric, NULL, &path));
 * ```
 *
 * \par Safety
 * `evaluate` must be non-null and valid until `copp_path_free`.
 * `user_data` must remain valid for all callback calls. `out_path` must be
 * valid for one `CoppPath*` write.
 */
enum CoppStatus copp_path_from_parametric(size_t dim,
                                          double s_min,
                                          double s_max,
                                          CoppPathParametricFn evaluate,
                                          void *user_data,
                                          struct CoppPath **out_path);

/**
 * Build a path from a C callback that provides derivatives up to 2nd order.
 *
 * The callback operates on a batch of `n` path samples and must write
 * column-major `dim x n` output matrices (`data[row + col * dim]`) for `q`,
 * `dq`, and `ddq`. The resulting path can be evaluated or sampled up to 2nd
 * order. Third-order evaluation returns
 * `COPP_STATUS_PATH_UNSUPPORTED_DERIVATIVE_ORDER`.
 *
 * The callback pointer and `user_data` are borrowed by the created path and
 * must remain valid until `copp_path_free` is called. Calls into the callback
 * are serialized per path handle.
 *
 * On success, `*out_path` receives a non-null handle that must be released
 * with `copp_path_free`.
 *
 * # Example
 * The example below wraps a one-dimensional external evaluator that provides
 * `q`, `dq`, and `ddq`.
 *
 * ```c
 * static enum CoppStatus eval_path_2nd(
 *     void *user_data,
 *     size_t dim,
 *     size_t n,
 *     const double *s,
 *     double *q,
 *     double *dq,
 *     double *ddq)
 * {
 *     for (size_t j = 0; j < n; ++j) {
 *         q[0 + j * dim] = s[j];
 *         dq[0 + j * dim] = 1.0;
 *         ddq[0 + j * dim] = 0.0;
 *     }
 *     return COPP_STATUS_OK;
 * }
 *
 * struct CoppPath *path = NULL;
 * check(copp_path_from_evaluator_2nd(1, 0.0, 1.0, eval_path_2nd, NULL, &path));
 * ```
 *
 * \par Safety
 * `evaluate_2nd` must be non-null and valid until `copp_path_free`.
 * `user_data` must remain valid for all callback calls. `out_path` must be
 * valid for one `CoppPath*` write.
 */
enum CoppStatus copp_path_from_evaluator_2nd(size_t dim,
                                             double s_min,
                                             double s_max,
                                             CoppPathEvaluate2ndFn evaluate_2nd,
                                             void *user_data,
                                             struct CoppPath **out_path);

/**
 * Build a path from C callbacks that provide derivatives up to 3rd order.
 *
 * `evaluate_3rd` is required. `evaluate_2nd` may be null; when it is null,
 * second-order evaluation calls `evaluate_3rd` internally and discards `dddq`.
 * Both callbacks operate on a batch of `n` path samples and must write
 * column-major `dim x n` output matrices (`data[row + col * dim]`).
 *
 * The callback pointers and `user_data` are borrowed by the created path and
 * must remain valid until `copp_path_free` is called. Calls into the callbacks
 * are serialized per path handle.
 *
 * On success, `*out_path` receives a non-null handle that must be released
 * with `copp_path_free`.
 *
 * # Example
 * The example below wraps a one-dimensional external evaluator that also
 * provides third derivatives.
 *
 * ```c
 * static enum CoppStatus eval_path_3rd(
 *     void *user_data,
 *     size_t dim,
 *     size_t n,
 *     const double *s,
 *     double *q,
 *     double *dq,
 *     double *ddq,
 *     double *dddq)
 * {
 *     for (size_t j = 0; j < n; ++j) {
 *         q[0 + j * dim] = s[j] * s[j];
 *         dq[0 + j * dim] = 2.0 * s[j];
 *         ddq[0 + j * dim] = 2.0;
 *         dddq[0 + j * dim] = 0.0;
 *     }
 *     return COPP_STATUS_OK;
 * }
 *
 * struct CoppPath *path = NULL;
 * check(copp_path_from_evaluator_3rd(1, 0.0, 1.0, NULL, eval_path_3rd, NULL, &path));
 * ```
 *
 * \par Safety
 * `evaluate_3rd` must be non-null and valid until `copp_path_free`.
 * `evaluate_2nd`, when non-null, must follow the same lifetime rule.
 * `user_data` must remain valid for all callback calls. `out_path` must be
 * valid for one `CoppPath*` write.
 */
enum CoppStatus copp_path_from_evaluator_3rd(size_t dim,
                                             double s_min,
                                             double s_max,
                                             CoppPathEvaluate2ndFn evaluate_2nd,
                                             CoppPathEvaluate3rdFn evaluate_3rd,
                                             void *user_data,
                                             struct CoppPath **out_path);

/**
 * Return the path dimension.
 *
 * \par Safety
 * `path` must be a non-null handle created by this module.
 * `out_dim` must be valid for one `size_t` write.
 */
enum CoppStatus copp_path_dim(const struct CoppPath *path, size_t *out_dim);

/**
 * Return the valid path parameter range.
 *
 * \par Safety
 * `path` must be a non-null handle created by this module.
 * `out_s_min` and `out_s_max` must be valid for one `double` write each.
 */
enum CoppStatus copp_path_s_range(const struct CoppPath *path,
                                  double *out_s_min,
                                  double *out_s_max);

/**
 * Evaluate `q`, `dq`, and `ddq` at the supplied path parameters.
 *
 * Output matrices are column-major with shape `dim x s.len` and must be
 * released with `copp_matrix_f64_free`.
 *
 * # Example
 * The example below evaluates second-order path derivatives and reads one
 * column-major output entry.
 *
 * ```c
 * double s_eval[] = {0.0, 0.5, 1.0};
 * struct CoppMatrixF64 q = {0};
 * struct CoppMatrixF64 dq = {0};
 * struct CoppMatrixF64 ddq = {0};
 *
 * check(copp_path_evaluate_up_to_2nd(
 *     path,
 *     (struct CoppSliceF64){s_eval, 3},
 *     &q,
 *     &dq,
 *     &ddq));
 *
 * double q_axis0_at_sample1 = q.data[0 + 1 * q.rows];
 * copp_matrix_f64_free(ddq);
 * copp_matrix_f64_free(dq);
 * copp_matrix_f64_free(q);
 * ```
 *
 * \par Safety
 * `path` must be a non-null handle created by this module.
 * `s.data` must be valid for `s.len` reads when non-empty. Output pointers
 * must be valid for one `CoppMatrixF64` write each.
 */
enum CoppStatus copp_path_evaluate_up_to_2nd(const struct CoppPath *path,
                                             struct CoppSliceF64 s,
                                             struct CoppMatrixF64 *out_q,
                                             struct CoppMatrixF64 *out_dq,
                                             struct CoppMatrixF64 *out_ddq);

/**
 * Evaluate `q`, `dq`, `ddq`, and `dddq` at the supplied path parameters.
 *
 * Output matrices are column-major with shape `dim x s.len` and must be
 * released with `copp_matrix_f64_free`.
 *
 * # Example
 * The example below evaluates a third-order path and releases all returned
 * matrices.
 *
 * ```c
 * struct CoppMatrixF64 q = {0}, dq = {0}, ddq = {0}, dddq = {0};
 * check(copp_path_evaluate_up_to_3rd(path, s_slice, &q, &dq, &ddq, &dddq));
 * copp_matrix_f64_free(dddq);
 * copp_matrix_f64_free(ddq);
 * copp_matrix_f64_free(dq);
 * copp_matrix_f64_free(q);
 * ```
 *
 * \par Safety
 * `path` must be a non-null handle created by this module.
 * `s.data` must be valid for `s.len` reads when non-empty. Output pointers
 * must be valid for one `CoppMatrixF64` write each.
 */
enum CoppStatus copp_path_evaluate_up_to_3rd(const struct CoppPath *path,
                                             struct CoppSliceF64 s,
                                             struct CoppMatrixF64 *out_q,
                                             struct CoppMatrixF64 *out_dq,
                                             struct CoppMatrixF64 *out_ddq,
                                             struct CoppMatrixF64 *out_dddq);

/**
 * Release a path handle created by this module.
 *
 * Passing null is allowed and has no effect.
 *
 * \par Safety
 * `path` must either be null or a live path handle that has not already been
 * freed.
 */
void copp_path_free(struct CoppPath *path);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* COPP_PATH_H */
