function result = solve_expert(problem, options)
%SOLVE_EXPERT Solve COPP2-SOCP and return Clarabel diagnostics.
%
% RESULT = copp.solver.copp2_socp.solve_expert(PROBLEM) returns a Result
% object. RESULT.a is available only when RESULT.has_a is true; raw Clarabel
% vectors and status fields are still returned for non-accepted statuses.
arguments
    problem (1,1) copp.solver.copp2_socp.Problem
    options (1,1) copp.clarabel.Options = copp.solver.copp2_socp.Options()
end

[robot_id, idx_s_start, idx_s_final, a_start, a_final, ...
    objective_kinds, objective_weights, ...
    objective_alpha_lengths, objective_beta_lengths, objective_normalize_lengths, ...
    objective_alpha_data, objective_beta_data, objective_normalize_data] = problem.native_descriptor();
option_args = options.native_descriptor();

[has_a, a, x, z, s_vec, status_code, obj_val, obj_val_dual, solve_time, ...
    iterations, r_prim, r_dual, objective_value, objective_terms, ...
    method_code, threads, direct, nnz_a, nnz_l] = copp.internal.copp_mex( ...
    'copp2_socp_solve_expert', ...
    robot_id, ...
    idx_s_start, ...
    idx_s_final, ...
    a_start, ...
    a_final, ...
    objective_kinds, ...
    objective_weights, ...
    objective_alpha_lengths, ...
    objective_beta_lengths, ...
    objective_normalize_lengths, ...
    objective_alpha_data, ...
    objective_beta_data, ...
    objective_normalize_data, ...
    option_args{:});

linsolver = struct( ...
    'method', direct_solve_method_name(method_code), ...
    'threads', double(threads), ...
    'direct', logical(direct), ...
    'nnz_a', double(nnz_a), ...
    'nnz_l', double(nnz_l));

result = copp.solver.copp2_socp.Result( ...
    logical(has_a), ...
    a, ...
    x, ...
    z, ...
    s_vec, ...
    copp.internal.clarabel_solver_status_name(status_code), ...
    obj_val, ...
    obj_val_dual, ...
    solve_time, ...
    iterations, ...
    r_prim, ...
    r_dual, ...
    linsolver, ...
    objective_value, ...
    objective_terms);
end

function name = direct_solve_method_name(code)
name = copp.internal.clarabel_direct_solve_method_name(code);
end
