function a = solve(problem, options)
%SOLVE Solve a COPP2-SOCP problem and return the node a(s) profile.
%
% A = copp.solver.copp2_socp.solve(PROBLEM) solves PROBLEM with default
% Options. A is returned as a column vector with length PROBLEM.s_len. Each
% entry stores a(k) = (ds/dt)^2 at one station in PROBLEM.idx_s_interval.
%
% A = ...solve(PROBLEM, OPTIONS) forwards explicit COPP2-SOCP status policy
% options. This non-expert entry returns only the accepted profile. Use
% solve_expert() when application code needs raw Clarabel diagnostics.
arguments
    problem (1,1) copp.solver.copp2_socp.Problem
    options (1,1) copp.clarabel.Options = copp.solver.copp2_socp.Options()
end

[robot_id, idx_s_start, idx_s_final, a_start, a_final, ...
    objective_kinds, objective_weights, ...
    objective_alpha_lengths, objective_beta_lengths, objective_normalize_lengths, ...
    objective_alpha_data, objective_beta_data, objective_normalize_data] = problem.native_descriptor();
option_args = options.native_descriptor();

a = copp.internal.copp_mex( ...
    'copp2_socp_solve', ...
    robot_id, ...
    idx_s_start, ...
    idx_s_final, ...
    a_start, ...
    a_final, ...
    objective_kinds, ...
    objective_weights, ...
    objective_alpha_lengths, ...
    objective_beta_lengths, ...
    objective_normalize_lengths, ...
    objective_alpha_data, ...
    objective_beta_data, ...
    objective_normalize_data, ...
    option_args{:});
end
