function a = solve(problem, options)
%SOLVE Solve a TOPP2-RA problem and return the node a(s) profile.
%
% A = copp.solver.topp2_ra.solve(PROBLEM) solves PROBLEM with default
% Options. A is returned as a column vector with length PROBLEM.s_len. Each
% entry stores a(k) = (ds/dt)^2 at one station in PROBLEM.idx_s_interval.
%
% A = ...solve(PROBLEM, OPTIONS) forwards explicit TOPP2-RA numerical options.
%
% The native solver borrows PROBLEM.robot during this call only. The Robot must
% still be valid when solve() is invoked.
arguments
    problem (1,1) copp.solver.topp2_ra.Problem
    options (1,1) copp.solver.topp2_ra.Options = copp.solver.topp2_ra.Options()
end

[robot_id, idx_s_start, idx_s_final, a_start, a_final] = problem.native_descriptor();
a = copp.internal.copp_mex( ...
    'topp2_ra_solve', ...
    robot_id, ...
    idx_s_start, ...
    idx_s_final, ...
    a_start, ...
    a_final, ...
    options.lp_feas_tol, ...
    options.a_cmp_abs_tol, ...
    options.a_cmp_rel_tol, ...
    char(options.verbosity));
end
