[package]
name = "copp-python"
version = "0.2.0"
edition = "2024"
publish = false

[lib]
name = "copp"
crate-type = ["cdylib"]

[dependencies]
copp = { path = "../.." }
clarabel = "0.11.1"
pyo3 = { version = "0.23", features = ["abi3-py310", "extension-module"] }
numpy = "0.23"
ndarray = "0.16"
nalgebra = "0.34.1"
