function profile = solve(problem, options)
%SOLVE Solve a TOPP3-LP problem and return a Profile3rd.
%
% PROFILE = copp.solver.topp3_lp.solve(PROBLEM) solves PROBLEM with
% default Options and returns a copp.Profile3rd object. PROFILE.a stores
% (ds/dt)^2 at stations and PROFILE.b stores d2s/dt2. Both fields are
% PROBLEM.s_len-by-1 double column vectors.
%
% PROBLEM may be the shared copp.solver.topp3.Problem descriptor or the
% solver-specific topp3_lp.Problem facade. The facade is recommended for
% readability but is not required by the type contract.
%
% Lazy linearization:
%   This call linearizes third-order constraints using PROBLEM.a_linearization
%   and mutates the native Robot's internal third-order constraint cache.
%   Constructing PROBLEM does not mutate the Robot cache.
arguments
    problem (1,1) copp.solver.topp3.Problem
    options (1,1) copp.clarabel.Options = copp.solver.topp3_lp.Options()
end

[robot_id, idx_s_start, a_linearization, a_start, a_final, b_start, b_final, ...
    num_stationary_max_start, num_stationary_max_end, a_linearization_floor] = problem.native_descriptor();
option_args = options.native_descriptor();

[a, b, num_stationary_start, num_stationary_end] = copp.internal.copp_mex( ...
    'topp3_lp_solve', ...
    robot_id, ...
    idx_s_start, ...
    a_linearization, ...
    a_start, ...
    a_final, ...
    b_start, ...
    b_final, ...
    num_stationary_max_start, ...
    num_stationary_max_end, ...
    a_linearization_floor, ...
    option_args{:});

profile = copp.Profile3rd(a, b, ...
    num_stationary=[num_stationary_start, num_stationary_end]);
end
