function profile = solve(problem, options)
%SOLVE Solve a COPP3-SOCP problem and return a Profile3rd.
%
% PROFILE.a and PROFILE.b are PROBLEM.s_len-by-1 double column vectors. This
% call linearizes third-order constraints using PROBLEM.a_linearization and
% mutates the native Robot's third-order cache.
arguments
    problem (1,1) copp.solver.copp3_socp.Problem
    options (1,1) copp.clarabel.Options = copp.solver.copp3_socp.Options()
end

[robot_id, idx_s_start, a_linearization, a_start, a_final, b_start, b_final, ...
    num_stationary_max_start, num_stationary_max_end, a_linearization_floor, ...
    objective_kinds, objective_weights, objective_alpha_lengths, ...
    objective_beta_lengths, objective_normalize_lengths, objective_alpha_data, ...
    objective_beta_data, objective_normalize_data] = problem.native_descriptor();
option_args = options.native_descriptor();

[a, b, num_stationary_start, num_stationary_end] = copp.internal.copp_mex( ...
    'copp3_socp_solve', ...
    robot_id, idx_s_start, a_linearization, a_start, a_final, b_start, b_final, ...
    num_stationary_max_start, num_stationary_max_end, a_linearization_floor, ...
    objective_kinds, objective_weights, objective_alpha_lengths, objective_beta_lengths, ...
    objective_normalize_lengths, objective_alpha_data, objective_beta_data, objective_normalize_data, ...
    option_args{:});

profile = copp.Profile3rd(a, b, ...
    num_stationary=[num_stationary_start, num_stationary_end]);
end
