function reach = backward(problem, options)
%BACKWARD Compute backward-only TOPP2 reachable intervals.
%
% REACH = copp.solver.reach_set2.backward(PROBLEM) returns a ReachSet
% containing a_max and a_min over PROBLEM.idx_s_interval. Both vectors are
% PROBLEM.s_len-by-1 double columns.
arguments
    problem (1,1) copp.solver.reach_set2.Problem
    options (1,1) copp.solver.reach_set2.Options = copp.solver.reach_set2.Options()
end

[robot_id, idx_s_start, idx_s_final, a_start, a_final] = problem.native_descriptor();
[a_max, a_min] = copp.internal.copp_mex( ...
    'reach_set2_backward', ...
    robot_id, ...
    idx_s_start, ...
    idx_s_final, ...
    a_start, ...
    a_final, ...
    options.lp_feas_tol, ...
    options.a_cmp_abs_tol, ...
    options.a_cmp_rel_tol, ...
    char(options.verbosity));

reach = copp.solver.reach_set2.ReachSet(a_max, a_min);
end
